name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: 'artifactory.eanadev.org' # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: ${{ secrets.REPO_USERNAME }} # env variable for username in deploy
          server-password: ${{ secrets.REPO_PASSWORD }} # env variable for token in deploy
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build - clean jacoco verify
        run: >
          mvn --batch-mode --update-snapshots
          clean
          org.jacoco:jacoco-maven-plugin:prepare-agent
          verify
      - name: Sonar
        run: >
          mvn --batch-mode
          org.jacoco:jacoco-maven-plugin:report
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=stz-test
          sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Deploy(Runs on main,master,develop)
        #if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'}}
        run: >
          mvn --batch-mode
          -Dmaven.main.skip=true
          -Dmaven.test.skip=true
          -Dmaven.install.skip=true
          deploy

