name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build - clean jacoco verify
        run: >
          mvn --batch-mode --update-snapshots
          clean
          org.jacoco:jacoco-maven-plugin:prepare-agent
          verify
      - name: Sonar
        run: >
          mvn --batch-mode
          org.jacoco:jacoco-maven-plugin:report
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=stz-test
          sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Prepare Settings Deploy
        run: >
          mkdir -p ~/.m2 &&
          echo "<settings><servers><server><id>${REPO_ID}</id><username>${REPO_USERNAME}</username><password>${REPO_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
        env:
          REPO_ID: artifactory.eanadev.org
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'}}
        run: >
          mvn --batch-mode
          -Dmaven.main.skip=true
          -Dmaven.test.skip=true
          -Dmaven.install.skip=true
          deploy

