name: DEPLOY LIBRARIES

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Prepare Settings Deploy
        run: >
          mkdir -p ~/.m2 &&
          echo "<settings><servers><server><id>${REPO_ID}</id><username>${REPO_USERNAME}</username><password>${REPO_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
        env:
          REPO_ID: artifactory.eanadev.org
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
      - name: Deploy(Runs on main,master,develop)
        run: >
          mvn --batch-mode
          -Dmaven.test.skip=true
          -Dmaven.install.skip=true
          deploy